# This file was generated by GoReleaser. DO NOT EDIT.
cask "amadeus" do
  version "0.0.12"

  on_macos do
    on_intel do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_darwin_amd64.tar.gz"
      sha256 "783b8ab64f00df0a77988cf264567a957d9c24eab31fe3a82c969288bcb0d94f"
    end
    on_arm do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_darwin_arm64.tar.gz"
      sha256 "f0e58bb99a65c33162b96e50a5a56ff2c2276a5707970af9ceb7da243dbfe00e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_linux_amd64.tar.gz"
      sha256 "634a6ecd61b50d8912160a30a0966782bd9147faf1e786ff6463c963e7dc7723"
    end
    on_arm do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_linux_arm64.tar.gz"
      sha256 "f4373bc8e92c7d1f06c3a610a58936f824be847c6f462a4559cbe265445818dc"
    end
  end

  name "amadeus"
  desc "Divergence meter for your codebase"
  homepage "https://github.com/hironow/amadeus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amadeus"

  # No zap stanza required

end
