# This file was generated by GoReleaser. DO NOT EDIT.
cask "amadeus" do
  name "amadeus"
  desc "Divergence meter for your codebase"
  homepage "https://github.com/hironow/amadeus"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "amadeus"

  on_macos do
    on_intel do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_darwin_amd64.tar.gz"
      sha256 "d39c336a846cb933ec34905fb86b86717eb7d902c4e6f9c92ef2c34869cdf4a2"
    end
    on_arm do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_darwin_arm64.tar.gz"
      sha256 "d44225d36a6cd6a76709713991e897816d198aea34d40bcda1436f4829f1d7ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_linux_amd64.tar.gz"
      sha256 "6d883b56f8997b235851e64e530deacdfaf7dab95a5c30e868e7f3d5961cdd97"
    end
    on_arm do
      url "https://github.com/hironow/amadeus/releases/download/v#{version}/amadeus_#{version}_linux_arm64.tar.gz"
      sha256 "afa8bcbe306864f65641410d5be0796113b4dc792f9e39f62e7565d5ae43a41d"
    end
  end

  # No zap stanza required
end
