# This file was generated by GoReleaser. DO NOT EDIT.
cask "paintress" do
  name "paintress"
  desc "Claude Code expedition orchestrator"
  homepage "https://github.com/hironow/paintress"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paintress"
  binary "paintress-tg"
  binary "paintress-discord"
  binary "paintress-slack"

  on_macos do
    on_intel do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_darwin_amd64.tar.gz"
      sha256 "57f9bb27541881c439e6f0b7c3935341b6df1038f3e48ab9cb7547991102f0e8"
    end
    on_arm do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_darwin_arm64.tar.gz"
      sha256 "7f54b37098b0cc509109ae925f3fa179606b11244716cad45f9d9becda1a8036"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_linux_amd64.tar.gz"
      sha256 "971e40c1daed6a0cae99b34282b8c1807790a79f2d7c7d1feda3bd1a4665dce3"
    end
    on_arm do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_linux_arm64.tar.gz"
      sha256 "1ee19533342a72dc56e3c3d7598acbcf626767c43f7032802d7644f40edde9ff"
    end
  end

  # No zap stanza required
end
