# This file was generated by GoReleaser. DO NOT EDIT.
cask "paintress" do
  name "paintress"
  desc "Claude Code expedition orchestrator"
  homepage "https://github.com/hironow/paintress"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paintress"
  binary "paintress-tg"
  binary "paintress-discord"
  binary "paintress-slack"

  on_macos do
    on_intel do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_darwin_amd64.tar.gz"
      sha256 "ecf5070b4080850cc2cace1eb78b4d8f9ed4d2eefcbe462834435e48ec5ac9d3"
    end
    on_arm do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_darwin_arm64.tar.gz"
      sha256 "5397cb4f395d072559e55b757ccc5d91c4bb372fcafbfcb4c4263c31b5b1cb77"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_linux_amd64.tar.gz"
      sha256 "ebcaeaa098aeb358cc7178e7e1fbad9a6577bb6940376f929ad0f8fe7a079e09"
    end
    on_arm do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_linux_arm64.tar.gz"
      sha256 "32c4f820ec47f1f2bcfbbd2274acf0ff7ed65221a2dc22b3dd4c663730246a0d"
    end
  end

  # No zap stanza required
end
