# This file was generated by GoReleaser. DO NOT EDIT.
cask "paintress" do
  name "paintress"
  desc "Claude Code expedition orchestrator"
  homepage "https://github.com/hironow/paintress"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "paintress"
  binary "paintress-tg"
  binary "paintress-discord"
  binary "paintress-slack"

  on_macos do
    on_intel do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_darwin_amd64.tar.gz"
      sha256 "2c2ddc047ac569553957415ca96226c8c4b81f5608415cf4e98ff5bd2066c555"
    end
    on_arm do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_darwin_arm64.tar.gz"
      sha256 "154f2f2916729bcd4babd931fd245629cb808593de1a40d6cb084eb3068a6024"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_linux_amd64.tar.gz"
      sha256 "060be16f1be0d616615cc57fcc61337f9cc2e46d235a7a98d4144b16c9b7b765"
    end
    on_arm do
      url "https://github.com/hironow/paintress/releases/download/v#{version}/paintress_#{version}_linux_arm64.tar.gz"
      sha256 "512281970d25b4228489c140982298ef4a6dd9f3a74715a41744b69504aab56e"
    end
  end

  # No zap stanza required
end
