# This file was generated by GoReleaser. DO NOT EDIT.
cask "phonewave" do
  name "phonewave"
  desc "D-Mail courier daemon"
  homepage "https://github.com/hironow/phonewave"
  version "0.0.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phonewave"

  on_macos do
    on_intel do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_darwin_amd64.tar.gz"
      sha256 "fa21d415065140ca2266769a7e6df7b5669809be5920e96a776819295fe56b55"
    end
    on_arm do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_darwin_arm64.tar.gz"
      sha256 "d322c527f4cb0886a7d806df0f557c104765d5b2d3ccb6313799c79e8e87c07b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_linux_amd64.tar.gz"
      sha256 "79610b9e23deb679a794d43f44a6ee2e4f43b24594312f339b06b13db9765b86"
    end
    on_arm do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_linux_arm64.tar.gz"
      sha256 "b9b0726a4a20dcb58f6f2e3fa8d0c64bf1facd1fdf14280aabf95725828c1b93"
    end
  end

  # No zap stanza required
end
