# This file was generated by GoReleaser. DO NOT EDIT.
cask "phonewave" do
  name "phonewave"
  desc "D-Mail courier daemon"
  homepage "https://github.com/hironow/phonewave"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phonewave"

  on_macos do
    on_intel do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_darwin_amd64.tar.gz"
      sha256 "00db2f607da4e769d42493c3b68145062fc665bfd4dbe7c55266b567135f501d"
    end
    on_arm do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_darwin_arm64.tar.gz"
      sha256 "c224813aef690bf5dda3a2dd1b4a650f32b57611030e5b4a0f241d9fb06cd6b4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_linux_amd64.tar.gz"
      sha256 "455e42a3815763a74fd42f3032d8f8cb1855b8444d1bb86da487551cac1c0c5a"
    end
    on_arm do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_linux_arm64.tar.gz"
      sha256 "81832648271181915b6427cee15df33e02b0da8b71db65973b52acc25453529a"
    end
  end

  # No zap stanza required
end
