# This file was generated by GoReleaser. DO NOT EDIT.
cask "phonewave" do
  name "phonewave"
  desc "D-Mail courier daemon"
  homepage "https://github.com/hironow/phonewave"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phonewave"

  on_macos do
    on_intel do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_darwin_amd64.tar.gz"
      sha256 "79c4ede5dca18417bd4d7a7ea26ee1d405ce56e00ac35889e0ec112a788cde79"
    end
    on_arm do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_darwin_arm64.tar.gz"
      sha256 "a3ab106772fe80e8ca12f9ce6ad7a04bd9e85a7327d64738055a606227797c45"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_linux_amd64.tar.gz"
      sha256 "f87df0b567c35af6bf89be707e957cc8719795a8f6f1da745d19eb3ff0eead0e"
    end
    on_arm do
      url "https://github.com/hironow/phonewave/releases/download/v#{version}/phonewave_#{version}_linux_arm64.tar.gz"
      sha256 "46ccf306f0901caf6b28939df59948c57dd03713470b52573bf0369eef89c252"
    end
  end

  # No zap stanza required
end
