# This file was generated by GoReleaser. DO NOT EDIT.
cask "sightjack" do
  name "sightjack"
  desc "SIREN-inspired issue architecture tool for Linear"
  homepage "https://github.com/hironow/sightjack"
  version "0.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sightjack"

  on_macos do
    on_intel do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_darwin_amd64.tar.gz"
      sha256 "ee08bfff82ad35da84a68d0135f78d23c56cdd3ed4fabd1455373c5232f4aea4"
    end
    on_arm do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_darwin_arm64.tar.gz"
      sha256 "ca494dbe2a5b72bb78bfc7dddd3211aeab5d472b0626548dca8c67723eebf7c6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_linux_amd64.tar.gz"
      sha256 "9cbd397a3d84dab950413c916bb3df58f1a8cffeb932866929cb0874c6621a24"
    end
    on_arm do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_linux_arm64.tar.gz"
      sha256 "8894f399d94bcfee8d91b38c05161eb41fd17e5c98a61421fc0f10606f3abeb9"
    end
  end

  # No zap stanza required
end
