# This file was generated by GoReleaser. DO NOT EDIT.
cask "sightjack" do
  name "sightjack"
  desc "SIREN-inspired issue architecture tool for Linear"
  homepage "https://github.com/hironow/sightjack"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sightjack"

  on_macos do
    on_intel do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_darwin_amd64.tar.gz"
      sha256 "4406b32ea3c7e61aabde7ea6abd0e773d9a952ec70069b628d5c5c26fedfb3d4"
    end
    on_arm do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_darwin_arm64.tar.gz"
      sha256 "e25b94b5315b319d8e082690615e1843316cd97ba1d6f7bead3a802f6ad9da36"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_linux_amd64.tar.gz"
      sha256 "8e93950569f998201e27c3e7d710444237ffbdafdbf605697bbeaa18e5ec16e0"
    end
    on_arm do
      url "https://github.com/hironow/sightjack/releases/download/v#{version}/sightjack_#{version}_linux_arm64.tar.gz"
      sha256 "32b27ac80bbc9d227a5368f8016c71a36e367357700b33e293a06aa112864baa"
    end
  end

  # No zap stanza required
end
