# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amadeus < Formula
  desc "Divergence meter for your codebase"
  homepage "https://github.com/hironow/amadeus"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hironow/amadeus/releases/download/v0.0.1/amadeus_0.0.1_darwin_amd64.tar.gz"
      sha256 "555dcfb31a69ed3246b6b7025b45a4af2208fd1e5580185f033942bbabb3b61d"

      define_method(:install) do
        bin.install "amadeus"
        generate_completions_from_executable(bin/"amadeus", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hironow/amadeus/releases/download/v0.0.1/amadeus_0.0.1_darwin_arm64.tar.gz"
      sha256 "38bb12ede5993ee54bef35474eed16be01ec12e5b72e2e041fc08d9acb444b57"

      define_method(:install) do
        bin.install "amadeus"
        generate_completions_from_executable(bin/"amadeus", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/amadeus/releases/download/v0.0.1/amadeus_0.0.1_linux_amd64.tar.gz"
      sha256 "4e2b22e58622b3f2a96cfef78311747bde4b0feba1b22104952d73824f588889"
      define_method(:install) do
        bin.install "amadeus"
        generate_completions_from_executable(bin/"amadeus", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/amadeus/releases/download/v0.0.1/amadeus_0.0.1_linux_arm64.tar.gz"
      sha256 "592b8a69804fda25cb5fc81c4f5d87f43d588759ab3f14b087a8524d52d624f1"
      define_method(:install) do
        bin.install "amadeus"
        generate_completions_from_executable(bin/"amadeus", "completion")
      end
    end
  end

  test do
    system "#{bin}/amadeus", "version"
  end
end
