# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paintress < Formula
  desc "Claude Code expedition orchestrator"
  homepage "https://github.com/hironow/paintress"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hironow/paintress/releases/download/v0.0.1/paintress_0.0.1_darwin_amd64.tar.gz"
      sha256 "e1d4a27a72b822857f7fe0bc346d8cc372a291a8e3fea91b8af37c087abe07b9"

      define_method(:install) do
        bin.install "paintress"
        bin.install "paintress-tg"
        bin.install "paintress-discord"
        bin.install "paintress-slack"
        generate_completions_from_executable(bin/"paintress", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hironow/paintress/releases/download/v0.0.1/paintress_0.0.1_darwin_arm64.tar.gz"
      sha256 "d2ac3a4759b61c404e5265be811f7f1ca6979d83ca995b07254c0e262c0ccedd"

      define_method(:install) do
        bin.install "paintress"
        bin.install "paintress-tg"
        bin.install "paintress-discord"
        bin.install "paintress-slack"
        generate_completions_from_executable(bin/"paintress", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/paintress/releases/download/v0.0.1/paintress_0.0.1_linux_amd64.tar.gz"
      sha256 "8e0c68e90b6b7e9ce4bf4c24623b210572c09bfc7a503fe1c1e6572761cf291d"
      define_method(:install) do
        bin.install "paintress"
        bin.install "paintress-tg"
        bin.install "paintress-discord"
        bin.install "paintress-slack"
        generate_completions_from_executable(bin/"paintress", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/paintress/releases/download/v0.0.1/paintress_0.0.1_linux_arm64.tar.gz"
      sha256 "f53a72ecf9530a8c1af2451b8795002230bb79d079cffc89f468fa4b84e4988e"
      define_method(:install) do
        bin.install "paintress"
        bin.install "paintress-tg"
        bin.install "paintress-discord"
        bin.install "paintress-slack"
        generate_completions_from_executable(bin/"paintress", "completion")
      end
    end
  end

  test do
    system "#{bin}/paintress", "version"
  end
end
