# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phonewave < Formula
  desc "D-Mail courier daemon"
  homepage "https://github.com/hironow/phonewave"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hironow/phonewave/releases/download/v0.0.1/phonewave_0.0.1_darwin_amd64.tar.gz"
      sha256 "4b69d9d92fe01d18c10d5fe0e598fa7c7113e2d2cb75d6df71004d08c365c4be"

      define_method(:install) do
        bin.install "phonewave"
        generate_completions_from_executable(bin/"phonewave", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hironow/phonewave/releases/download/v0.0.1/phonewave_0.0.1_darwin_arm64.tar.gz"
      sha256 "3b9de41af67b482b5a7dad26a65addde970a280c054deea42760831d49ab697a"

      define_method(:install) do
        bin.install "phonewave"
        generate_completions_from_executable(bin/"phonewave", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/phonewave/releases/download/v0.0.1/phonewave_0.0.1_linux_amd64.tar.gz"
      sha256 "5c3b63fd13b1587eaf656acb2f6a97aed83a942186c2610ba236bca9be1abb64"
      define_method(:install) do
        bin.install "phonewave"
        generate_completions_from_executable(bin/"phonewave", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/phonewave/releases/download/v0.0.1/phonewave_0.0.1_linux_arm64.tar.gz"
      sha256 "4601d03e062dbbbfe32f0e01a23ec00eb30b8ff97625d7827c0492a4918f888f"
      define_method(:install) do
        bin.install "phonewave"
        generate_completions_from_executable(bin/"phonewave", "completion")
      end
    end
  end

  test do
    system "#{bin}/phonewave", "version"
  end
end
