# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sightjack < Formula
  desc "SIREN-inspired issue architecture tool for Linear"
  homepage "https://github.com/hironow/sightjack"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hironow/sightjack/releases/download/v0.0.1/sightjack_0.0.1_darwin_amd64.tar.gz"
      sha256 "39ffdbd2621cde8923a576595c5aff4e02d94d894af33efce01b676ee2a93d2b"

      define_method(:install) do
        bin.install "sightjack"
        generate_completions_from_executable(bin/"sightjack", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hironow/sightjack/releases/download/v0.0.1/sightjack_0.0.1_darwin_arm64.tar.gz"
      sha256 "36a626eb50a75b0d197571d39b2a78290dacb57158d1765a8e397ee6a02039ab"

      define_method(:install) do
        bin.install "sightjack"
        generate_completions_from_executable(bin/"sightjack", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/sightjack/releases/download/v0.0.1/sightjack_0.0.1_linux_amd64.tar.gz"
      sha256 "6d3ee4d20bf542b4dd640b3883db3dafe999dcdf833c6958495d2ed08570f42b"
      define_method(:install) do
        bin.install "sightjack"
        generate_completions_from_executable(bin/"sightjack", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hironow/sightjack/releases/download/v0.0.1/sightjack_0.0.1_linux_arm64.tar.gz"
      sha256 "fb517473aaf180e8a0247de12425ceeec407145112e0d27233a3215aea379c39"
      define_method(:install) do
        bin.install "sightjack"
        generate_completions_from_executable(bin/"sightjack", "completion")
      end
    end
  end

  test do
    system "#{bin}/sightjack", "version"
  end
end
